services:
  taskero-backend_db:
    image: postgres:13.22-alpine3.22
    container_name: 'taskero-backend_db'
    volumes:
      - ./data-docker/postgresql/data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${DB_USERNAME}', '-d', '${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

  taskero-backend_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: 'taskero-backend_app'
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./generated:/app/generated
      - ./logs:/app/logs
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    depends_on:
      taskero-backend_db:
        condition: service_healthy
